# ─────────────────────────────────────────────
#  tools/zone_drawer.py
#  Interactive zone polygon editor
#  Click to add points → Right-click to finish zone
#  Press 's' to save → Press 'q' to quit
# ─────────────────────────────────────────────

import cv2
import json
import numpy as np
from pathlib import Path

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.settings import ZONES_PATH

ZONE_PRESETS = [
    {"id": "Z1", "name": "Entry / Exit",    "color": [0, 255, 0]},
    {"id": "Z2", "name": "Open Area",       "color": [255, 165, 0]},
    {"id": "Z3", "name": "Restricted Zone", "color": [255, 0, 0]},
    {"id": "Z4", "name": "Perimeter",       "color": [128, 0, 128]},
]

current_zone_idx = 0
current_points   = []
saved_zones      = []
frame_ref        = None


def mouse_callback(event, x, y, flags, param):
    global current_points, current_zone_idx, saved_zones, frame_ref

    if event == cv2.EVENT_LBUTTONDOWN:
        current_points.append([x, y])
        print(f"  Added point: ({x}, {y})")

    elif event == cv2.EVENT_RBUTTONDOWN:
        # Finish current zone
        if len(current_points) >= 3:
            zone_def = ZONE_PRESETS[current_zone_idx % len(ZONE_PRESETS)]
            saved_zones.append({
                "id":            zone_def["id"],
                "name":          zone_def["name"],
                "color":         zone_def["color"],
                "polygon":       list(current_points),
                "alert_on_entry": zone_def["id"] == "Z3",
                "loiter_threshold_override": 5 if zone_def["id"] == "Z3" else None,
            })
            print(f"✅ Zone '{zone_def['name']}' saved with {len(current_points)} points.")
            current_points = []
            current_zone_idx += 1

            if current_zone_idx >= len(ZONE_PRESETS):
                print("\n✅ All zones defined! Press 's' to save.")


def draw_ui(frame: np.ndarray) -> np.ndarray:
    vis = frame.copy()

    # Draw saved zones
    for z in saved_zones:
        poly  = np.array(z["polygon"], dtype=np.int32)
        color = tuple(reversed(z["color"]))   # BGR
        cv2.polylines(vis, [poly], True, color, 2)
        cx, cy = poly.mean(axis=0).astype(int)
        cv2.putText(vis, z["name"], (cx - 30, cy),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1)

    # Draw current in-progress zone
    if current_points:
        for pt in current_points:
            cv2.circle(vis, pt, 5, (0, 255, 255), -1)
        if len(current_points) > 1:
            for i in range(1, len(current_points)):
                cv2.line(vis, current_points[i-1], current_points[i], (0, 255, 255), 1)

    # Instructions overlay
    if current_zone_idx < len(ZONE_PRESETS):
        zone_def = ZONE_PRESETS[current_zone_idx % len(ZONE_PRESETS)]
        msg = f"Drawing: {zone_def['name']} ({zone_def['id']}) | LClick=add pt | RClick=finish zone"
    else:
        msg = "All zones done! Press 's' to save, 'q' to quit."

    cv2.rectangle(vis, (0, 0), (vis.shape[1], 30), (0, 0, 0), -1)
    cv2.putText(vis, msg, (6, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)

    return vis


def run(video_path: str):
    global frame_ref

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"ERROR: Cannot open {video_path}")
        return

    ret, frame = cap.read()
    cap.release()
    if not ret:
        print("ERROR: Cannot read first frame.")
        return

    frame_ref = frame.copy()
    h, w      = frame.shape[:2]
    print(f"\n🎥 Video frame: {w}x{h}")
    print("─" * 50)
    print("  LEFT CLICK  → add polygon point")
    print("  RIGHT CLICK → finish current zone")
    print("  's'         → save zones.json")
    print("  'r'         → restart current zone")
    print("  'q'         → quit without saving")
    print("─" * 50)
    print(f"\nDefine zones in order:")
    for z in ZONE_PRESETS:
        print(f"  {z['id']}: {z['name']}")
    print()

    cv2.namedWindow("Zone Drawer", cv2.WINDOW_NORMAL)
    cv2.setMouseCallback("Zone Drawer", mouse_callback)

    while True:
        vis = draw_ui(frame_ref)
        cv2.imshow("Zone Drawer", vis)
        key = cv2.waitKey(20) & 0xFF

        if key == ord("s"):
            _save_zones(w, h)
            break
        elif key == ord("r"):
            current_points.clear()
            print("↩ Current zone reset.")
        elif key == ord("q"):
            print("Quit without saving.")
            break

    cv2.destroyAllWindows()


def _save_zones(frame_w: int, frame_h: int):
    out = {
        "_comment": f"Zones defined on {frame_w}x{frame_h} frame.",
        "_note":    "Generated by tools/zone_drawer.py",
        "zones":    saved_zones,
    }
    Path(ZONES_PATH).parent.mkdir(parents=True, exist_ok=True)
    with open(ZONES_PATH, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\n✅ Zones saved to: {ZONES_PATH}")
    print(f"   {len(saved_zones)} zones defined.")


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python tools/zone_drawer.py <video_path>")
        print("Example: python tools/zone_drawer.py data/videos/sample.mp4")
        sys.exit(1)
    run(sys.argv[1])
